//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropuestasDonacionesHorasTrabajo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PropuestasDonacionesHorasTrabajo()
        {
            this.DonacionesHorasTrabajoes = new HashSet<DonacionesHorasTrabajo>();
        }
    
        public int IdPropuestaDonacionHorasTrabajo { get; set; }
        public int IdPropuesta { get; set; }
        public int CantidadHoras { get; set; }
        public string Profesion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonacionesHorasTrabajo> DonacionesHorasTrabajoes { get; set; }
        public virtual Propuesta Propuesta { get; set; }
    }
}
