//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropuestasDonacionesInsumo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PropuestasDonacionesInsumo()
        {
            this.DonacionesInsumos = new HashSet<DonacionesInsumo>();
        }
    
        public int IdPropuestaDonacionInsumo { get; set; }
        public int IdPropuesta { get; set; }
        public string Nombre { get; set; }
        public int Cantidad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonacionesInsumo> DonacionesInsumos { get; set; }
        public virtual Propuesta Propuesta { get; set; }
    }
}
