//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Denuncia> Denuncias { get; set; }
        public virtual DbSet<DonacionesHorasTrabajo> DonacionesHorasTrabajoes { get; set; }
        public virtual DbSet<DonacionesInsumo> DonacionesInsumos { get; set; }
        public virtual DbSet<DonacionesMonetaria> DonacionesMonetarias { get; set; }
        public virtual DbSet<MotivoDenuncia> MotivoDenuncias { get; set; }
        public virtual DbSet<Propuesta> Propuestas { get; set; }
        public virtual DbSet<PropuestasDonacionesHorasTrabajo> PropuestasDonacionesHorasTrabajoes { get; set; }
        public virtual DbSet<PropuestasDonacionesInsumo> PropuestasDonacionesInsumos { get; set; }
        public virtual DbSet<PropuestasDonacionesMonetaria> PropuestasDonacionesMonetarias { get; set; }
        public virtual DbSet<PropuestasReferencia> PropuestasReferencias { get; set; }
        public virtual DbSet<PropuestasValoracione> PropuestasValoraciones { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
    }
}
